-- 8c-3: `users.friend_id` STAYS. This migration is a deliberate no-op.
--
-- ⚠️ DO NOT REWRITE THIS TO DROP THE COLUMN. It was attempted three times against the
-- remote database on 2026-07-30 and cannot work there. Every attempt rolled back
-- cleanly — production integrity was re-verified each time — but each one took the
-- database briefly offline for nothing.
--
-- WHY IT CANNOT WORK
--
-- `friend_id TEXT UNIQUE` is declared inline, so SQLite refuses
-- `ALTER TABLE users DROP COLUMN friend_id` outright:
--     cannot drop UNIQUE column: "friend_id"                          [attempt 1]
-- That forces a create-copy-drop-rename. But EIGHT tables carry
-- `REFERENCES users(id)` — identities, sessions, profiles, profile_stats,
-- feed_events, comments, comment_reactions, episode_votes — so dropping the parent
-- violates all of them:
--     FOREIGN KEY constraint failed                                [attempts 2, 3]
--
-- Both escapes fail on remote D1:
--   * `PRAGMA defer_foreign_keys` defers ROW checks to commit. Dropping a parent
--     table is a SCHEMA violation, which deferral does not cover. Reproduced in a
--     local SQLite loaded with this exact schema pulled from D1.
--   * `PRAGMA foreign_keys = OFF` works in plain SQLite — including
--     `wrangler d1 migrations apply --local`, where all twelve migrations apply and
--     the result verifies clean (column gone, UNIQUE index intact, no FK violations).
--     ⚠️ **Remote D1 does not honour it.** That local/remote difference is what made
--     attempt 3 look safe when it was not: a green `--local` run is NOT evidence for
--     `--remote` when PRAGMAs are involved.
--
-- The only route left is rebuilding all NINE tables to strip and restore the FK
-- clauses — a large, risky operation on live data to reclaim a column nothing reads.
--
-- WHY LEAVING IT COSTS NOTHING
--
-- 8c-3's behavioural half is already deployed and verified by live curl: no code
-- reads `users.friend_id`. The claim-check that used it is gone, `handleClaimFriendId`
-- and `PUT /api/me/friend-id` are gone, and the client stopped writing it. The column
-- is inert — four rows of dead storage.
--
-- The one thing that ever depended on it — the friend-card claim-check, whose removal
-- left a card's self-declared `friendId` unverified — closes with the client-side
-- friendId→userId migration (M1–M7), NOT by reclaiming this column. Dropping it here
-- would not have advanced that by a single step.
--
-- If it must eventually go, fold it into a migration that is rebuilding `users` for
-- another reason anyway, and rebuild the child tables in the same pass.
SELECT 1;
